"""empty message

Revision ID: 701dc9848b19
Revises: db155105219d
Create Date: 2024-01-09 18:08:55.219276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701dc9848b19'
down_revision = 'db155105219d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
